// <auto-generated />
using System;
using ComissionTB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ComissionTB.Migrations
{
    [DbContext(typeof(ComissionDbContext))]
    [Migration("20210308045032_mg-000")]
    partial class mg000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ComissionTB.Data.AppRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descript")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ComissionTB.Data.AppUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("dolgnid_dl")
                        .HasColumnType("int");

                    b.Property<int>("tabNo")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime?>("userDismis")
                        .HasColumnType("datetime2");

                    b.Property<string>("userFio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("userPriem")
                        .HasColumnType("datetime2");

                    b.Property<string>("userSecName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("dolgnid_dl");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ComissionTB.Data.Dolgn", b =>
                {
                    b.Property<int>("id_dl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dlName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_dl");

                    b.HasIndex("dlName")
                        .IsUnique();

                    b.ToTable("tDolgn");
                });

            modelBuilder.Entity("ComissionTB.Models.Akt", b =>
                {
                    b.Property<int>("aktNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("aktDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("cexid_cex")
                        .HasColumnType("int");

                    b.HasKey("aktNo");

                    b.HasIndex("cexid_cex");

                    b.ToTable("tAkt");
                });

            modelBuilder.Entity("ComissionTB.Models.Cex", b =>
                {
                    b.Property<int>("id_cex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cexName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_cex");

                    b.HasIndex("cexName")
                        .IsUnique();

                    b.ToTable("cex");
                });

            modelBuilder.Entity("ComissionTB.Models.Obj", b =>
                {
                    b.Property<int>("id_obj")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("objInvNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("objName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("objNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pomid_pom")
                        .HasColumnType("int");

                    b.HasKey("id_obj");

                    b.HasIndex("pomid_pom");

                    b.ToTable("tObject");
                });

            modelBuilder.Entity("ComissionTB.Models.Pom", b =>
                {
                    b.Property<int>("id_pom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("cexid_cex")
                        .HasColumnType("int");

                    b.Property<decimal?>("pomArea")
                        .HasMaxLength(10)
                        .HasPrecision(2)
                        .HasColumnType("decimal(2)");

                    b.Property<int?>("pomKindid_pk")
                        .HasColumnType("int");

                    b.Property<string>("pomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_pom");

                    b.HasIndex("cexid_cex");

                    b.HasIndex("pomKindid_pk");

                    b.ToTable("tPom");
                });

            modelBuilder.Entity("ComissionTB.Models.PomKind", b =>
                {
                    b.Property<int>("id_pk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pkName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("pkTreb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_pk");

                    b.HasIndex("pkName")
                        .IsUnique();

                    b.ToTable("pomKind");
                });

            modelBuilder.Entity("ComissionTB.Models.Predp", b =>
                {
                    b.Property<int>("prNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("aktNo")
                        .HasColumnType("int");

                    b.Property<int?>("appUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("prDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("prIspDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("prIspNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prOcen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("prText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("prNo");

                    b.HasIndex("aktNo");

                    b.HasIndex("appUserId");

                    b.ToTable("tPredp");
                });

            modelBuilder.Entity("ComissionTB.Models.Sostav", b =>
                {
                    b.Property<int>("id_st")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("aktNo")
                        .HasColumnType("int");

                    b.Property<bool>("isPreds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isSekr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("userId")
                        .HasColumnType("int");

                    b.HasKey("id_st");

                    b.HasIndex("aktNo");

                    b.HasIndex("userId");

                    b.ToTable("tSostav");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ComissionTB.Data.AppUsers", b =>
                {
                    b.HasOne("ComissionTB.Data.Dolgn", "dolgn")
                        .WithMany("users")
                        .HasForeignKey("dolgnid_dl");

                    b.Navigation("dolgn");
                });

            modelBuilder.Entity("ComissionTB.Models.Akt", b =>
                {
                    b.HasOne("ComissionTB.Models.Cex", "cex")
                        .WithMany("akts")
                        .HasForeignKey("cexid_cex");

                    b.Navigation("cex");
                });

            modelBuilder.Entity("ComissionTB.Models.Obj", b =>
                {
                    b.HasOne("ComissionTB.Models.Pom", "pom")
                        .WithMany("objs")
                        .HasForeignKey("pomid_pom");

                    b.Navigation("pom");
                });

            modelBuilder.Entity("ComissionTB.Models.Pom", b =>
                {
                    b.HasOne("ComissionTB.Models.Cex", "cex")
                        .WithMany("poms")
                        .HasForeignKey("cexid_cex");

                    b.HasOne("ComissionTB.Models.PomKind", "pomKind")
                        .WithMany("poms")
                        .HasForeignKey("pomKindid_pk");

                    b.Navigation("cex");

                    b.Navigation("pomKind");
                });

            modelBuilder.Entity("ComissionTB.Models.Predp", b =>
                {
                    b.HasOne("ComissionTB.Models.Akt", "akt")
                        .WithMany("predps")
                        .HasForeignKey("aktNo");

                    b.HasOne("ComissionTB.Data.AppUsers", "appUser")
                        .WithMany()
                        .HasForeignKey("appUserId");

                    b.Navigation("akt");

                    b.Navigation("appUser");
                });

            modelBuilder.Entity("ComissionTB.Models.Sostav", b =>
                {
                    b.HasOne("ComissionTB.Models.Akt", "akt")
                        .WithMany("sostavs")
                        .HasForeignKey("aktNo");

                    b.HasOne("ComissionTB.Data.AppUsers", "user")
                        .WithMany("sostavs")
                        .HasForeignKey("userId");

                    b.Navigation("akt");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("ComissionTB.Data.AppRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("ComissionTB.Data.AppUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("ComissionTB.Data.AppUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("ComissionTB.Data.AppRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComissionTB.Data.AppUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("ComissionTB.Data.AppUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComissionTB.Data.AppUsers", b =>
                {
                    b.Navigation("sostavs");
                });

            modelBuilder.Entity("ComissionTB.Data.Dolgn", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("ComissionTB.Models.Akt", b =>
                {
                    b.Navigation("predps");

                    b.Navigation("sostavs");
                });

            modelBuilder.Entity("ComissionTB.Models.Cex", b =>
                {
                    b.Navigation("akts");

                    b.Navigation("poms");
                });

            modelBuilder.Entity("ComissionTB.Models.Pom", b =>
                {
                    b.Navigation("objs");
                });

            modelBuilder.Entity("ComissionTB.Models.PomKind", b =>
                {
                    b.Navigation("poms");
                });
#pragma warning restore 612, 618
        }
    }
}
